# Generated by Django 5.0.6 on 2024-07-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('baseimg', models.ImageField(upload_to='assets/')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
