# Generated by Django 5.0.6 on 2024-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='id',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='baseimg',
            field=models.ImageField(upload_to='./media/'),
        ),
    ]
