# Generated by Django 5.0.6 on 2024-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renapp', '0003_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
