# Generated by Django 5.0.6 on 2024-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renapp', '0004_alter_shoppingcart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
